project_id = "team-tasks"
#enabled = true

[api]
enabled = true
port = 55421
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

#[api.tls]
#enabled = false

[db]
#enabled = true
port = 55432           # main Postgres DB
shadow_port = 55433    # shadow DB
major_version = 15

[db.pooler]
enabled = true
port = 55434           # connection pooler
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

[realtime]
enabled = true
#port = 55424

[studio]
enabled = true
port = 55423
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]  # Mailpit (email testing service)
enabled = true
port = 55435        # Web UI
smtp_port = 55436   # SMTP
pop3_port = 55437   # POP3

[storage]
enabled = true
#port = 55425
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6
password_requirements = ""

[auth.rate_limit]
email_sent = 2
sms_sent = 30
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
web3 = 30

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[edge_runtime]
enabled = true
#port = 55428
policy = "oneshot"
inspector_port = 55429
deno_version = 1

[analytics]
enabled = true
port = 55430
backend = "postgres"

