name: Deploy
on: { push: { branches: [ "main" ] }, workflow_dispatch: {} }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Build & Push Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/team-tasks:latest
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/team-tasks:latest
            docker stop team-tasks || true
            docker rm team-tasks || true
            echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
            echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
            docker run -d --name team-tasks --env-file .env -p 80:3000 ghcr.io/${{ github.repository_owner }}/team-tasks:latest
