name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Build and push Docker image
      - name: Build & Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/systems-geek/team-tasks-aws:latest
          echo "Building and pushing $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy on EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT }}
          script: |
            echo "Pulling latest Docker image..."
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}
            docker pull ghcr.io/systems-geek/team-tasks-aws:latest

            echo "Stopping old container..."
            docker stop team-tasks-aws || true
            docker rm team-tasks-aws || true

            echo "Running new container..."
            docker run -d --name team-tasks-aws \
              -p 80:3000 \
              -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
              -e SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
              ghcr.io/systems-geek/team-tasks-aws:latest
